### ISSUE TITLE
is 2-bit max2769b array elemnts enought for anti jamming

### ISSUE THREAD

**Issue by iceberg1369** [tomojitakasu/PocketSDR#8]
I was reading the future works of pocket-sdr. I would like to know whether 2-bit adc arrays is adequate for antijamming mitigation?

**Comment by tomojitakasu** [comment]
According to the following paper, there are small differences among floating, 3-bit and 2-bit ADC for 7-elements CRPA.

https://web.stanford.edu/group/scpnt/gpslab/pubs/papers/DeLorenzo_IONGNSS_2004.pdf

However, optimized LNA gain may be necessary for low-resolution ADC. I plan to use manual gain control provided by MAX2769B instead of AGC.
